---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-fitness-data-producer
spec:
  selector:
    matchLabels:
      app: kafka-fitness-data-producer
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-fitness-data-producer
    spec:
      containers:
      - name: kafka-fitness-data-producer
        image: tubpeng/kafka-fitness-data-producer
        ports:
        - containerPort: 7778
        env:
        - name: KAFKA_DOMAIN_NAME
          value: fitness-data-pipeline-cp-kafka-headless
      - name: fitness-data-donation
        image: tubpeng/fitness-data-donation
        ports:
        - containerPort: 7777
        env:
        - name: STRAVA_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: access-secrets
              key: strava_client_id
        - name: STRAVA_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: access-secrets
              key: strava_client_secret

---
apiVersion: v1
kind: Service
metadata:
  name: fitness-data-donation-service
spec:
  type: NodePort
  selector:
    app: kafka-fitness-data-producer
  ports:
    - port: 7777
      targetPort: 7777
      name: donation
    - port: 7778
      targetPort: 7778
      name: producer
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      # nodePort: 30007

---
apiVersion: v1
kind: Secret
metadata:
  name: access-secrets
type: Opaque
stringData:
  strava_client_id: "$STRAVA_CLIENT_ID"
  strava_client_secret: "$STRAVA_CLIENT_SECRET"