---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-fitness-data-producer
spec:
  selector:
    matchLabels:
      app: kafka-fitness-data-producer
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-fitness-data-producer
    spec:
      containers:
      - name: kafka-fitness-data-producer
        image: tubpeng/kafka-fitness-data-producer
        ports:
        - containerPort: 7778
        env:
        - name: KAFKA_DOMAIN_NAME
          value: "${PIPELINE_CP_PREFIX}-cp-kafka-headless"
      - name: fitness-data-donation
        image: tubpeng/fitness-data-donation
        ports:
        - containerPort: 7777
        env:
        - name: STRAVA_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: access-secrets
              key: strava_client_id
        - name: STRAVA_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: access-secrets
              key: strava_client_secret

---
apiVersion: v1
kind: Service
metadata:
  name: fitness-data-producer-service
spec:
  type: ClusterIP
  selector:
    app: kafka-fitness-data-producer
  ports:
    - protocol: TCP
      port: 7778
      targetPort: 7778

---
apiVersion: v1
kind: Service
metadata:
  name: fitness-data-donation-service
spec:
  type: LoadBalancer
  selector:
    app: kafka-fitness-data-producer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 7777

---
apiVersion: v1
kind: Secret
metadata:
  name: access-secrets
type: Opaque
stringData:
  strava_client_id: "$STRAVA_CLIENT_ID"
  strava_client_secret: "$STRAVA_CLIENT_SECRET"