version: '3.4'

services:
  donation:
    build:
      context: .
      dockerfile: donation-platform/Dockerfile
    environment:
      - STRAVA_CLIENT_ID=$STRAVA_CLIENT_ID
      - STRAVA_CLIENT_SECRET=$STRAVA_CLIENT_SECRET
      - PRODUCER_DOMAIN_NAME=producer
    ports:
      - '7777:7777'
    container_name: fitness-data-donation
    networks:
      - kafka-net

  producer:
    build:
      context: .
      dockerfile: kafka-producer/Dockerfile
    environment:
      - KAFKA_DOMAIN_NAME=kafka-server
    ports:
      - '7778:7778'
    container_name: kafka-fitness-data-producer
    networks:
      - kafka-net

  zookeeper-server:
    image: 'bitnami/zookeeper:latest'
    networks:
      - kafka-net
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka-server:
    image: 'bitnami/kafka:latest'
    networks:
      - kafka-net
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper-server

networks:
  kafka-net:
    driver: bridge