version: '3.4'

services:
  donation:
    build:
      context: .
      dockerfile: donation-platform/Dockerfile
    environment:
      - STRAVA_CLIENT_ID=$STRAVA_CLIENT_ID
      - STRAVA_CLIENT_SECRET=$STRAVA_CLIENT_SECRET
      - PRODUCER_DOMAIN_NAME=producer
    ports:
      - '7777:7777'
    container_name: fitness-data-donation

  producer:
    build:
      context: .
      dockerfile: kafka-producer/Dockerfile
    environment:
      - KAFKA_DOMAIN_NAME=kafka
    ports:
      - '7778:7778'
    container_name: kafka-fitness-data-producer

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: host.docker.internal
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock